// Evaluation parameters. This file is (re)generated by the tuner; keep the format.
#pragma once

int mg_value[6] = {82, 337, 365, 477, 1025, 0};
int eg_value[6] = {94, 281, 297, 512, 936, 0};
int mg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
      90,  126,   69,   87,   68,  118,   42,   -3,
     -14,   -1,   18,   39,   73,   48,   17,  -28,
     -22,    5,   14,   29,   31,   20,   25,  -31,
     -35,    6,    3,   20,   25,   14,   18,  -33,
     -18,  -12,    4,   -2,   11,   11,   25,   -4,
     -27,    7,  -28,  -31,  -23,   16,   30,  -30,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int eg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
     170,  181,  166,  126,  147,  124,  157,  195,
      86,   92,   93,   75,   64,   45,   74,   92,
      24,   16,   21,   13,    6,   12,   25,   25,
      21,    1,    5,    1,    1,    0,   11,   -9,
      12,   -1,    2,    9,   -8,  -13,   -9,  -16,
      21,   16,    0,    2,    5,   -8,   10,  -15,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int mg_knight_table[64] = {
    -167,  -89,  -26,  -57,   53, -105,  -15, -107,
     -73,  -41,   64,   44,   31,   54,   15,  -17,
     -47,   68,   29,   73,   76,  137,   81,   36,
      -1,    9,   27,   45,   29,   77,   26,   30,
     -21,   -4,   24,    5,   36,   11,   29,  -16,
     -15,   -1,    4,   18,   27,   25,   33,  -24,
     -29,  -61,   -4,  -11,    7,   26,  -22,  -11,
     -97,  -29,  -50,  -41,   -9,  -36,  -11,  -23,
};
int eg_knight_table[64] = {
     -58,  -38,   -5,  -36,  -39,  -35,  -63,  -99,
     -25,  -16,  -17,    6,   -1,  -33,  -16,  -52,
     -24,  -12,    2,   17,   -9,   -1,  -11,  -49,
      -9,   11,   30,   14,   30,   11,   16,  -10,
     -26,  -14,   24,   33,   24,   25,   12,  -26,
     -15,    5,   -9,   23,   18,    5,  -12,  -14,
     -42,  -28,   -2,    3,    6,  -12,  -31,  -52,
     -21,  -43,  -15,   -7,  -30,  -26,  -42,  -64,
};
int mg_bishop_table[64] = {
     -37,    4,  -74,  -37,  -17,  -42,   15,   -8,
     -34,    8,  -18,   -5,   38,   67,   18,  -55,
     -24,   29,   35,   48,   43,   58,   45,    6,
      -4,   13,   11,   42,   45,   45,   -1,  -10,
       2,   21,    5,   18,   26,    4,   18,   12,
      -8,    7,    7,    7,    6,   19,   26,    2,
      12,    7,   24,   -8,   15,   29,   25,    1,
     -41,  -11,   -6,  -29,   -5,   -4,  -31,  -29,
};
int eg_bishop_table[64] = {
     -22,  -21,   -3,   -8,  -15,   -9,   -9,  -24,
     -16,  -12,    7,   -4,    5,   -5,   -4,  -22,
      10,  -16,   -8,    7,    6,   14,    8,   -4,
      -3,    1,    4,   17,   22,   10,   -5,   -6,
       2,   -5,    5,   27,   15,    2,  -11,   -1,
     -20,  -11,    0,   18,   21,   -5,    1,  -23,
      -6,  -10,    1,    7,   -4,   -1,  -23,  -27,
     -15,  -17,  -31,  -13,   -1,   -8,    3,  -25,
};
int mg_rook_table[64] = {
      24,   34,   24,   43,   55,    1,   23,   51,
      19,   40,   50,   62,   72,   59,   18,   52,
       3,   27,   34,   44,    9,   37,   53,   24,
     -32,  -19,   -1,   18,   16,   27,  -16,  -12,
     -44,  -26,  -20,   -9,    1,    1,   -2,  -15,
     -53,  -17,   -8,   -9,   -5,    8,    3,  -25,
     -36,   -8,  -12,   -1,   -9,   19,  -14,  -63,
     -11,  -21,   -7,   25,    8,   -1,  -29,  -34,
};
int eg_rook_table[64] = {
       5,    2,   10,    7,    4,    4,    0,   13,
      19,   21,    5,   19,  -11,   -5,    0,   11,
      15,   15,   15,   13,   -4,  -11,  -13,    5,
      -4,   -5,    5,   -7,   -6,   -7,   -9,   -6,
      -5,   13,    0,   -4,  -13,  -14,  -16,   -3,
     -12,    8,    3,   -9,  -15,   -4,    0,   -8,
     -14,    2,    8,   10,  -17,   -1,  -11,    5,
      -1,   -6,   -5,   -9,  -13,   -5,   12,  -12,
};
int mg_queen_table[64] = {
     -36,   -8,   21,    4,   67,   36,   35,   53,
     -32,  -31,  -13,    9,  -24,   49,   36,   46,
     -21,  -17,   15,   16,   37,   64,   39,   65,
     -19,  -19,   -8,  -24,    7,    9,    6,   -7,
      -1,  -18,   -1,  -18,  -10,  -12,   -5,    5,
      -6,   10,   -3,    6,    3,   -6,    6,   -3,
     -27,  -16,    3,   -6,    0,   23,  -11,   -7,
       7,  -10,  -17,    2,   -7,  -17,  -31,  -42,
};
int eg_queen_table[64] = {
     -17,   30,   14,   35,   35,   19,    2,   28,
     -25,   12,   24,   49,   58,   17,   38,   -8,
     -12,   -2,    1,   57,   55,   43,   27,   17,
      11,   14,   32,   53,   65,   48,   65,   28,
     -10,   20,   11,   39,   39,   34,   31,   31,
      -8,  -19,   23,   14,   17,   25,    2,   13,
     -14,  -23,  -22,  -24,  -24,  -15,  -44,  -40,
     -25,  -36,  -30,  -35,  -13,  -24,  -20,  -33,
};
int mg_king_table[64] = {
     -65,   23,    8,  -23,  -64,  -42,   -6,    5,
      21,   -9,  -28,  -15,  -16,  -12,  -46,  -37,
     -17,   16,   -6,  -24,  -12,   14,   30,  -30,
     -25,  -28,  -20,  -19,  -38,  -17,  -22,  -44,
     -41,    7,  -35,  -31,  -38,  -36,  -25,  -43,
      -6,   -6,  -14,  -54,  -36,  -22,   -7,  -35,
       9,   15,   -8,  -56,  -51,   -8,    1,   16,
      -7,   44,   20,  -46,    0,  -36,   16,   22,
};
int eg_king_table[64] = {
     -74,  -35,  -26,  -26,  -19,    7,   -4,  -25,
     -20,    9,    6,    9,   17,   30,   15,    3,
      18,    9,   15,    7,   28,   53,   52,    5,
     -16,   14,   16,   35,   18,   41,   18,   -5,
     -10,    4,   29,   16,   35,   31,   17,   -3,
     -11,    5,    3,   13,   31,   24,   -1,  -17,
     -19,   -3,   12,    5,    6,   12,  -13,  -25,
     -45,  -26,  -13,   -3,  -28,  -22,  -32,  -35,
};
Score MobilityKnight[9] = {S(-42,-52), S(-22,-22), S(-4,-4), S(-12,6), S(12,14), S(18,20), S(24,24), S(30,26), S(36,26)};
Score MobilityBishop[14] = {S(-48,-68), S(-14,-22), S(-16,-22), S(-8,6), S(-2,14), S(4,20), S(8,10), S(12,14), S(30,18), S(16,20), S(34,22), S(20,22), S(22,24), S(40,40)};
Score MobilityRook[15] = {S(-58,-78), S(-16,-22), S(-4,-2), S(2,-4), S(-10,4), S(-8,12), S(-4,36), S(16,42), S(20,46), S(22,50), S(16,46), S(10,42), S(12,44), S(30,62), S(16,46)};
Score MobilityQueen[28] = {S(-30,-50), S(-28,-30), S(-20,-28), S(0,-18), S(-12,8), S(6,16), S(-8,22), S(-6,20), S(12,16), S(-2,20), S(0,24), S(18,42), S(4,28), S(21,46), S(22,48), S(7,50), S(8,52), S(9,38), S(10,56), S(11,40), S(12,42), S(29,58), S(14,60), S(31,60), S(32,62), S(33,62), S(18,48), S(35,64)};
Score PassedRank[8] = {S(0,0), S(-13,18), S(-13,23), S(13,35), S(33,68), S(68,118), S(102,162), S(0,0)};
Score PawnIsolated = S(-20,-22);
Score PawnDoubled = S(-16,-28);
Score PawnBackward = S(-16,-18);
Score PawnConnected[8] = {S(0,0), S(2,0), S(-2,10), S(2,-2), S(24,20), S(20,16), S(42,48), S(0,0)};
Score PawnPhalanx[8] = {S(0,0), S(-4,2), S(16,12), S(22,16), S(14,8), S(48,38), S(78,68), S(0,0)};
Score BishopPair = S(17,42);
Score RookOpenFile = S(38,2);
Score RookSemiOpenFile = S(14,0);
Score RookOnSeventh = S(18,33);
Score KnightOutpost = S(36,26);
Score BishopOutpost = S(10,2);
Score MinorBehindPawn = S(16,10);
Score ThreatByPawn = S(63,53);
Score ThreatMinorOnMajor = S(32,22);
Score ThreatRookOnQueen = S(22,12);
Score ThreatHanging = S(22,28);
Score ThreatByKing = S(23,48);
Score PawnPushThreat = S(26,20);
Score Tempo = S(16,0);
Score KingShield[3] = {S(16,-8), S(6,-8), S(14,8)};
Score KingOpenFile = S(-28,-8);
Score KingSemiOpenFile = S(-6,8);
int KingAttackWeight[6] = {0, 20, 4, 10, 22, 0};
int SafeCheckWeight[6] = {0, 22, 12, 32, 42, 0};
int KingDanger[5] = {464, 20, 32, 112, 28};

int* mg_tables[6] = {mg_pawn_table, mg_knight_table, mg_bishop_table, mg_rook_table, mg_queen_table, mg_king_table};
int* eg_tables[6] = {eg_pawn_table, eg_knight_table, eg_bishop_table, eg_rook_table, eg_queen_table, eg_king_table};

#define TE_S(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(Score)), 0}
#define TE_S1(x) {#x, (void*)&x, 1, 0}
#define TE_I(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(int)), 1}
#define TE_P(x) {#x, (void*)x, 64, 2}
std::vector<TuneEntry> tune_entries() {
    return {
        {"mg_value", (void*)mg_value, 6, 3}, {"eg_value", (void*)eg_value, 6, 3},
        TE_P(mg_pawn_table), TE_P(eg_pawn_table), TE_P(mg_knight_table), TE_P(eg_knight_table),
        TE_P(mg_bishop_table), TE_P(eg_bishop_table), TE_P(mg_rook_table), TE_P(eg_rook_table),
        TE_P(mg_queen_table), TE_P(eg_queen_table), TE_P(mg_king_table), TE_P(eg_king_table),
        TE_S(MobilityKnight), TE_S(MobilityBishop), TE_S(MobilityRook), TE_S(MobilityQueen),
        TE_S(PassedRank), TE_S1(PawnIsolated), TE_S1(PawnDoubled), TE_S1(PawnBackward),
        TE_S(PawnConnected), TE_S(PawnPhalanx), TE_S1(BishopPair), TE_S1(RookOpenFile), TE_S1(RookSemiOpenFile),
        TE_S1(RookOnSeventh), TE_S1(KnightOutpost), TE_S1(BishopOutpost), TE_S1(MinorBehindPawn),
        TE_S1(ThreatByPawn), TE_S1(ThreatMinorOnMajor), TE_S1(ThreatRookOnQueen), TE_S1(ThreatHanging),
        TE_S1(ThreatByKing), TE_S1(PawnPushThreat), TE_S1(Tempo), TE_S(KingShield), TE_S1(KingOpenFile),
        TE_S1(KingSemiOpenFile), TE_I(KingAttackWeight), TE_I(SafeCheckWeight), TE_I(KingDanger),
    };
}
