// Evaluation parameters. This file is (re)generated by the tuner; keep the format.
#pragma once

int mg_value[6] = {82, 337, 365, 477, 1025, 0};
int eg_value[6] = {94, 281, 297, 512, 936, 0};
int mg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
      98,  134,   61,   95,   68,  126,   34,  -11,
      -6,    7,   26,   31,   65,   56,   25,  -20,
     -14,   13,    6,   21,   23,   12,   17,  -23,
     -27,   -2,   -5,   12,   17,    6,   10,  -25,
     -26,   -4,   -4,  -10,    3,    3,   33,  -12,
     -35,   -1,  -20,  -23,  -15,   24,   38,  -22,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int eg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
     178,  173,  158,  134,  147,  132,  165,  187,
      94,  100,   85,   67,   56,   53,   82,   84,
      32,   24,   13,    5,   -2,    4,   17,   17,
      13,    9,   -3,   -7,   -7,   -8,    3,   -1,
       4,    7,   -6,    1,    0,   -5,   -1,   -8,
      13,    8,    8,   10,   13,    0,    2,   -7,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int mg_knight_table[64] = {
    -167,  -89,  -34,  -49,   61,  -97,  -15, -107,
     -73,  -41,   72,   36,   23,   62,    7,  -17,
     -47,   60,   37,   65,   84,  129,   73,   44,
      -9,   17,   19,   53,   37,   69,   18,   22,
     -13,    4,   16,   13,   28,   19,   21,   -8,
     -23,   -9,   12,   10,   19,   17,   25,  -16,
     -29,  -53,  -12,   -3,   -1,   18,  -14,  -19,
    -105,  -21,  -58,  -33,  -17,  -28,  -19,  -23,
};
int eg_knight_table[64] = {
     -58,  -38,  -13,  -28,  -31,  -27,  -63,  -99,
     -25,   -8,  -25,   -2,   -9,  -25,  -24,  -52,
     -24,  -20,   10,    9,   -1,   -9,  -19,  -41,
     -17,    3,   22,   22,   22,   11,    8,  -18,
     -18,   -6,   16,   25,   16,   17,    4,  -18,
     -23,   -3,   -1,   15,   10,   -3,  -20,  -22,
     -42,  -20,  -10,   -5,   -2,  -20,  -23,  -44,
     -29,  -51,  -23,  -15,  -22,  -18,  -50,  -64,
};
int mg_bishop_table[64] = {
     -29,    4,  -82,  -37,  -25,  -42,    7,   -8,
     -26,   16,  -18,  -13,   30,   59,   18,  -47,
     -16,   37,   43,   40,   35,   50,   37,   -2,
      -4,    5,   19,   50,   37,   37,    7,   -2,
      -6,   13,   13,   26,   34,   12,   10,    4,
       0,   15,   15,   15,   14,   27,   18,   10,
       4,   15,   16,    0,    7,   21,   33,    1,
     -33,   -3,  -14,  -21,  -13,  -12,  -39,  -21,
};
int eg_bishop_table[64] = {
     -14,  -21,  -11,   -8,   -7,   -9,  -17,  -24,
      -8,   -4,    7,  -12,   -3,  -13,   -4,  -14,
       2,   -8,    0,   -1,   -2,    6,    0,    4,
      -3,    9,   12,    9,   14,   10,    3,    2,
      -6,    3,   13,   19,    7,   10,   -3,   -9,
     -12,   -3,    8,   10,   13,    3,   -7,  -15,
     -14,  -18,   -7,   -1,    4,   -9,  -15,  -27,
     -23,   -9,  -23,   -5,   -9,  -16,   -5,  -17,
};
int mg_rook_table[64] = {
      32,   42,   32,   51,   63,    9,   31,   43,
      27,   32,   58,   62,   80,   67,   26,   44,
      -5,   19,   26,   36,   17,   45,   61,   16,
     -24,  -11,    7,   26,   24,   35,   -8,  -20,
     -36,  -26,  -12,   -1,    9,   -7,    6,  -23,
     -45,  -25,  -16,  -17,    3,    0,   -5,  -33,
     -44,  -16,  -20,   -9,   -1,   11,   -6,  -71,
     -19,  -13,    1,   17,   16,    7,  -37,  -26,
};
int eg_rook_table[64] = {
      13,   10,   18,   15,   12,   12,    8,    5,
      11,   13,   13,   11,   -3,    3,    8,    3,
       7,    7,    7,    5,    4,   -3,   -5,   -3,
       4,    3,   13,    1,    2,    1,   -1,    2,
       3,    5,    8,    4,   -5,   -6,   -8,  -11,
      -4,    0,   -5,   -1,   -7,  -12,   -8,  -16,
      -6,   -6,    0,    2,   -9,   -9,  -11,   -3,
      -9,    2,    3,   -1,   -5,  -13,    4,  -20,
};
int mg_queen_table[64] = {
     -28,    0,   29,   12,   59,   44,   43,   45,
     -24,  -39,   -5,    1,  -16,   57,   28,   54,
     -13,  -17,    7,    8,   29,   56,   47,   57,
     -27,  -27,  -16,  -16,   -1,   17,   -2,    1,
      -9,  -26,   -9,  -10,   -2,   -4,    3,   -3,
     -14,    2,  -11,   -2,   -5,    2,   14,    5,
     -35,   -8,   11,    2,    8,   15,   -3,    1,
      -1,  -18,   -9,   10,  -15,  -25,  -31,  -50,
};
int eg_queen_table[64] = {
      -9,   22,   22,   27,   27,   19,   10,   20,
     -17,   20,   32,   41,   58,   25,   30,    0,
     -20,    6,    9,   49,   47,   35,   19,    9,
       3,   22,   24,   45,   57,   40,   57,   36,
     -18,   28,   19,   47,   31,   34,   39,   23,
     -16,  -27,   15,    6,    9,   17,   10,    5,
     -22,  -23,  -30,  -16,  -16,  -23,  -36,  -32,
     -33,  -28,  -22,  -43,   -5,  -32,  -20,  -41,
};
int mg_king_table[64] = {
     -65,   23,   16,  -15,  -56,  -34,    2,   13,
      29,   -1,  -20,   -7,   -8,   -4,  -38,  -29,
      -9,   24,    2,  -16,  -20,    6,   22,  -22,
     -17,  -20,  -12,  -27,  -30,  -25,  -14,  -36,
     -49,   -1,  -27,  -39,  -46,  -44,  -33,  -51,
     -14,  -14,  -22,  -46,  -44,  -30,  -15,  -27,
       1,    7,   -8,  -64,  -43,  -16,    9,    8,
     -15,   36,   12,  -54,    8,  -28,   24,   14,
};
int eg_king_table[64] = {
     -74,  -35,  -18,  -18,  -11,   15,    4,  -17,
     -12,   17,   14,   17,   17,   38,   23,   11,
      10,   17,   23,   15,   20,   45,   44,   13,
      -8,   22,   24,   27,   26,   33,   26,    3,
     -18,   -4,   21,   24,   27,   23,    9,  -11,
     -19,   -3,   11,   21,   23,   16,    7,   -9,
     -27,  -11,    4,   13,   14,    4,   -5,  -17,
     -53,  -34,  -21,  -11,  -28,  -14,  -24,  -43,
};
Score MobilityKnight[9] = {S(-26,-36), S(-10,-6), S(-8,12), S(-4,22), S(12,14), S(14,24), S(20,24), S(22,18), S(16,10)};
Score MobilityBishop[14] = {S(-20,-36), S(-10,-22), S(0,6), S(4,22), S(6,22), S(16,36), S(16,42), S(8,46), S(10,50), S(0,48), S(18,54), S(4,50), S(54,36), S(8,48)};
Score MobilityRook[15] = {S(-50,-94), S(0,-50), S(4,14), S(14,28), S(10,36), S(20,44), S(20,52), S(24,58), S(32,62), S(34,66), S(32,70), S(34,74), S(44,76), S(30,78), S(48,58)};
Score MobilityQueen[28] = {S(-6,-26), S(-12,-54), S(-20,-44), S(-12,-34), S(-16,-24), S(-10,8), S(-8,-10), S(-14,16), S(-16,36), S(-6,44), S(-4,56), S(6,50), S(0,60), S(9,62), S(-2,64), S(-1,66), S(28,68), S(25,70), S(42,72), S(43,72), S(44,74), S(45,74), S(46,76), S(47,76), S(48,78), S(49,78), S(50,80), S(51,80)};
Score PassedRank[8] = {S(0,0), S(-13,34), S(3,39), S(-19,59), S(1,72), S(36,86), S(86,146), S(0,0)};
Score PawnIsolated = S(-4,-2);
Score PawnDoubled = S(-12,-32);
Score PawnBackward = S(-12,2);
Score PawnConnected[8] = {S(0,0), S(2,0), S(6,14), S(6,-2), S(12,4), S(28,0), S(42,16), S(0,0)};
Score PawnPhalanx[8] = {S(0,0), S(4,2), S(8,0), S(10,4), S(10,32), S(64,54), S(94,84), S(0,0)};
Score BishopPair = S(21,50);
Score RookOpenFile = S(26,30);
Score RookSemiOpenFile = S(14,32);
Score RookOnSeventh = S(6,37);
Score KnightOutpost = S(24,30);
Score BishopOutpost = S(2,14);
Score MinorBehindPawn = S(8,14);
Score ThreatByPawn = S(71,25);
Score ThreatMinorOnMajor = S(64,10);
Score ThreatRookOnQueen = S(54,-4);
Score ThreatHanging = S(30,44);
Score ThreatByKing = S(19,32);
Score PawnPushThreat = S(14,20);
Score Tempo = S(28,20);
Score KingShield[3] = {S(16,-12), S(6,-12), S(6,-16)};
Score KingOpenFile = S(-12,-20);
Score KingSemiOpenFile = S(-6,8);
int KingAttackWeight[6] = {0, 16, 12, 14, 22, 0};
int SafeCheckWeight[6] = {0, 54, 44, 64, 74, 0};
int KingDanger[5] = {368, 28, 32, 144, 16};

int* mg_tables[6] = {mg_pawn_table, mg_knight_table, mg_bishop_table, mg_rook_table, mg_queen_table, mg_king_table};
int* eg_tables[6] = {eg_pawn_table, eg_knight_table, eg_bishop_table, eg_rook_table, eg_queen_table, eg_king_table};

#define TE_S(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(Score)), 0}
#define TE_S1(x) {#x, (void*)&x, 1, 0}
#define TE_I(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(int)), 1}
#define TE_P(x) {#x, (void*)x, 64, 2}
std::vector<TuneEntry> tune_entries() {
    return {
        {"mg_value", (void*)mg_value, 6, 3}, {"eg_value", (void*)eg_value, 6, 3},
        TE_P(mg_pawn_table), TE_P(eg_pawn_table), TE_P(mg_knight_table), TE_P(eg_knight_table),
        TE_P(mg_bishop_table), TE_P(eg_bishop_table), TE_P(mg_rook_table), TE_P(eg_rook_table),
        TE_P(mg_queen_table), TE_P(eg_queen_table), TE_P(mg_king_table), TE_P(eg_king_table),
        TE_S(MobilityKnight), TE_S(MobilityBishop), TE_S(MobilityRook), TE_S(MobilityQueen),
        TE_S(PassedRank), TE_S1(PawnIsolated), TE_S1(PawnDoubled), TE_S1(PawnBackward),
        TE_S(PawnConnected), TE_S(PawnPhalanx), TE_S1(BishopPair), TE_S1(RookOpenFile), TE_S1(RookSemiOpenFile),
        TE_S1(RookOnSeventh), TE_S1(KnightOutpost), TE_S1(BishopOutpost), TE_S1(MinorBehindPawn),
        TE_S1(ThreatByPawn), TE_S1(ThreatMinorOnMajor), TE_S1(ThreatRookOnQueen), TE_S1(ThreatHanging),
        TE_S1(ThreatByKing), TE_S1(PawnPushThreat), TE_S1(Tempo), TE_S(KingShield), TE_S1(KingOpenFile),
        TE_S1(KingSemiOpenFile), TE_I(KingAttackWeight), TE_I(SafeCheckWeight), TE_I(KingDanger),
    };
}
