// Evaluation parameters. This file is (re)generated by the tuner; keep the format.
#pragma once

int mg_value[6] = {82, 337, 365, 477, 1025, 0};
int eg_value[6] = {94, 281, 297, 512, 936, 0};
int mg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
      70,  130,   33,   67,   40,   98,    6,  -39,
       6,    9,    0,   59,   71,   84,   -3,    0,
      -6,   -1,   16,   31,   31,   36,   21,  -41,
     -35,  -18,   -7,   12,   -3,    0,   -2,   -9,
     -24,  -22,   -8,   -6,   -7,    9,   11,  -12,
     -37,   -1,   -4,  -13,  -23,    4,   10,  -24,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int eg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
     150,  145,  134,  106,  119,  120,  137,  159,
      66,  104,   71,   51,   36,   53,  110,   68,
      52,   34,   31,   -1,    4,   16,   29,   29,
      33,   21,    3,   -7,   -5,   -4,   -5,   15,
      14,    5,    4,   -3,   -4,   -5,  -23,    2,
      37,   36,  -16,   38,   -7,   28,  -24,   -9,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int mg_knight_table[64] = {
    -177, -113,  -62,  -21,   69, -107,  -23, -103,
     -47,  -13,   74,    8,    3,   34,  -13,   11,
     -51,   32,   29,   61,   82,  101,   45,   72,
      19,    3,   33,   31,   21,   53,   20,   34,
      13,   32,   24,    9,   26,    5,    7,  -20,
     -21,  -13,  -12,  -16,   17,    1,   37,   -8,
     -57,  -25,   16,  -17,  -15,   38,  -42,  -33,
    -133,  -35,  -30,  -49,  -29,  -30,  -33,    5,
};
int eg_knight_table[64] = {
     -50,  -66,  -31,    0,  -11,  -55,  -35, -115,
     -47,  -20,  -35,  -30,  -19,  -43,  -12,  -56,
     -52,  -22,   22,    3,  -19,  -31,   -9,  -23,
      -5,   21,   -6,    4,   42,    1,  -18,  -18,
     -22,  -34,   20,   37,   28,   29,    8,  -22,
       5,  -21,    9,   -7,   38,   19,   -2,  -30,
     -40,  -34,   18,   17,   26,    8,    5,  -48,
     -57,  -37,  -51,  -15,   -6,   10,  -42,  -36,
};
int mg_bishop_table[64] = {
      -1,   32, -100,  -41,  -53,  -70,  -19,  -36,
     -34,  -12,  -16,    7,    2,   31,  -10,  -19,
     -44,   45,   15,   12,   37,   54,    9,   -6,
      -8,    3,   43,   22,    9,    9,   29,   10,
     -34,  -15,   17,   54,   30,   -8,   10,   24,
      14,   43,   31,    1,   -6,    9,    8,   14,
      32,   -3,    2,  -22,    9,    3,   25,   29,
     -43,   25,  -24,    7,   15,  -16,  -67,    5,
};
int eg_bishop_table[64] = {
     -42,  -17,  -33,   20,  -19,    9,   11,    4,
     -36,  -32,   11,  -16,   -7,  -41,   24,   14,
      -4,   20,  -28,  -27,   -8,   22,  -28,    4,
     -11,    3,  -12,   -5,    2,  -18,  -25,  -26,
      -4,  -25,   -3,    1,    9,  -16,  -31,   -1,
     -32,  -19,   20,  -12,   11,  -25,  -35,  -43,
     -40,  -30,    3,  -15,    0,    9,  -35,  -31,
      -3,  -13,  -35,  -31,   19,   12,  -33,   11,
};
int mg_rook_table[64] = {
      32,   42,   58,   23,   91,   27,   59,   71,
      55,    4,   30,   48,   52,   39,   -2,   70,
     -31,   47,   -2,    8,   45,   39,   33,   -2,
     -52,   15,    7,   28,   34,   63,   20,  -48,
     -40,  -54,  -36,  -29,   25,   -9,   20,    5,
     -33,    1,    6,   11,  -15,   28,  -33,  -35,
     -68,  -32,    0,   19,   25,  -17,   20,  -85,
     -21,   -5,  -17,    5,  -12,   -5,  -45,  -32,
};
int eg_rook_table[64] = {
      23,   18,    0,   -9,   12,    0,    4,    9,
     -11,    3,    9,    3,   13,    5,   32,   23,
      23,   -3,   17,    3,   10,  -19,  -15,   13,
      32,   -5,    5,  -13,  -16,  -21,    1,   30,
      31,   31,   24,    0,   13,   -2,   -6,  -11,
      12,   12,   13,    3,   -7,   -2,   -8,  -14,
      18,    0,  -28,  -26,    7,   -3,  -15,   25,
      -5,  -24,    1,  -23,  -19,   -5,   12,    0,
};
int mg_queen_table[64] = {
       0,   18,   55,   40,   87,   72,   71,   17,
       4,  -19,   11,   29,   12,   57,   56,   26,
      13,  -37,   35,   -4,   53,   84,   19,   53,
       1,  -13,  -30,   12,   23,   45,   26,  -27,
     -13,    2,    7,  -28,   10,   24,   13,   25,
      14,  -24,    3,    6,  -21,    4,   42,   31,
     -63,  -18,   13,    6,    8,  -13,   25,  -27,
      -7,    8,   19,  -12,  -15,   -7,  -13,  -22,
};
int eg_queen_table[64] = {
      19,   50,   50,   55,   55,   47,   38,   48,
      11,   48,   60,   69,   86,   27,   48,   22,
       6,   34,   37,   77,   75,   63,   45,   35,
      31,   46,   52,   73,   85,   68,   85,   64,
     -20,   54,   47,   75,   59,   62,   51,   51,
      10,  -17,   39,   34,   31,   35,   38,   23,
      -6,  -37,  -24,    6,  -14,    5,   -8,   -4,
      -7,    0,  -50,  -35,   23,   -4,    8,  -13,
};
int mg_king_table[64] = {
     -85,   -1,   44,  -43,  -28,  -42,   30,   41,
      33,  -29,  -30,    5,  -16,  -28,  -66,  -57,
     -33,    2,   30,   -4,    8,  -22,   -6,  -48,
     -21,  -32,   12,  -55,  -24,  -31,  -42,  -64,
     -27,  -19,  -11,  -59,  -74,  -36,  -59,  -79,
     -42,  -24,  -42,  -66,  -72,  -38,   -3,  -17,
       3,  -21,  -36,  -36,  -21,  -18,    1,   10,
     -43,   30,   20,  -30,    8,  -14,   26,   38,
};
int eg_king_table[64] = {
    -102,  -63,  -22,  -46,  -37,   -9,  -16,  -45,
     -40,  -11,  -12,   -1,    3,   10,    5,  -17,
     -18,  -11,   21,   41,   24,   51,   52,  -15,
     -34,   12,   52,   43,   44,   53,   30,  -25,
     -12,   -6,   37,   48,   53,   35,   25,  -39,
     -47,   13,   25,   29,   29,   30,  -13,   -5,
     -49,  -13,   22,   25,   10,    0,    5,  -13,
     -31,  -22,    7,   17,   -8,  -18,  -14,  -49,
};
Score MobilityKnight[9] = {S(-42,-4), S(-26,26), S(-18,18), S(-12,28), S(6,8), S(4,30), S(14,34), S(26,28), S(36,6)};
Score MobilityBishop[14] = {S(-32,-26), S(-24,10), S(-14,-20), S(-12,28), S(-2,32), S(4,22), S(2,28), S(0,26), S(8,34), S(-10,42), S(24,42), S(-28,36), S(62,48), S(-22,24)};
Score MobilityRook[15] = {S(-18,-86), S(-4,-22), S(6,18), S(6,32), S(10,48), S(8,66), S(18,54), S(24,66), S(30,68), S(22,76), S(32,70), S(20,74), S(48,72), S(48,88), S(48,62)};
Score MobilityQueen[28] = {S(26,6), S(-30,-30), S(-40,-76), S(-28,-36), S(-24,-56), S(-18,-20), S(-22,-16), S(-8,8), S(-6,32), S(4,40), S(0,86), S(-2,78), S(4,92), S(-3,94), S(6,96), S(23,98), S(46,100), S(51,102), S(72,104), S(73,104), S(74,106), S(77,106), S(78,108), S(79,96), S(80,100), S(65,72), S(76,54), S(29,56)};
Score PassedRank[8] = {S(0,0), S(-45,36), S(-29,27), S(-51,37), S(-1,56), S(16,82), S(54,114), S(0,0)};
Score PawnIsolated = S(-4,-2);
Score PawnDoubled = S(-26,-32);
Score PawnBackward = S(-14,6);
Score PawnConnected[8] = {S(0,0), S(2,0), S(8,6), S(12,8), S(14,22), S(26,-32), S(18,-16), S(0,0)};
Score PawnPhalanx[8] = {S(0,0), S(2,-10), S(6,4), S(12,8), S(20,6), S(56,82), S(126,116), S(0,0)};
Score BishopPair = S(19,76);
Score RookOpenFile = S(34,12);
Score RookSemiOpenFile = S(-2,46);
Score RookOnSeventh = S(-24,57);
Score KnightOutpost = S(38,12);
Score BishopOutpost = S(14,24);
Score MinorBehindPawn = S(8,18);
Score ThreatByPawn = S(75,23);
Score ThreatMinorOnMajor = S(64,22);
Score ThreatRookOnQueen = S(86,-36);
Score ThreatHanging = S(6,60);
Score ThreatByKing = S(37,0);
Score PawnPushThreat = S(28,12);
Score Tempo = S(26,20);
Score KingShield[3] = {S(40,-2), S(16,-2), S(12,-16)};
Score KingOpenFile = S(-4,-22);
Score KingSemiOpenFile = S(-6,0);
int KingAttackWeight[6] = {0, 28, 26, 24, 22, 0};
int SafeCheckWeight[6] = {0, 66, 42, 58, 96, 0};
int KingDanger[5] = {336, 50, 14, 176, 18};
Score BishopPawns = S(-4,2);
Score RookBehindPasser = S(32,44);
Score PawnStorm[4] = {S(0,0), S(4,22), S(-16,0), S(10,-6)};
Score KnightPawnCount = S(-3,13);
Score RookPawnCount = S(-2,-8);
Score Space = S(3,-14);
Score PassedBlocked = S(6,-40);

int* mg_tables[6] = {mg_pawn_table, mg_knight_table, mg_bishop_table, mg_rook_table, mg_queen_table, mg_king_table};
int* eg_tables[6] = {eg_pawn_table, eg_knight_table, eg_bishop_table, eg_rook_table, eg_queen_table, eg_king_table};

#define TE_S(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(Score)), 0}
#define TE_S1(x) {#x, (void*)&x, 1, 0}
#define TE_I(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(int)), 1}
#define TE_P(x) {#x, (void*)x, 64, 2}
std::vector<TuneEntry> tune_entries() {
    return {
        {"mg_value", (void*)mg_value, 6, 3}, {"eg_value", (void*)eg_value, 6, 3},
        TE_P(mg_pawn_table), TE_P(eg_pawn_table), TE_P(mg_knight_table), TE_P(eg_knight_table),
        TE_P(mg_bishop_table), TE_P(eg_bishop_table), TE_P(mg_rook_table), TE_P(eg_rook_table),
        TE_P(mg_queen_table), TE_P(eg_queen_table), TE_P(mg_king_table), TE_P(eg_king_table),
        TE_S(MobilityKnight), TE_S(MobilityBishop), TE_S(MobilityRook), TE_S(MobilityQueen),
        TE_S(PassedRank), TE_S1(PawnIsolated), TE_S1(PawnDoubled), TE_S1(PawnBackward),
        TE_S(PawnConnected), TE_S(PawnPhalanx), TE_S1(BishopPair), TE_S1(RookOpenFile), TE_S1(RookSemiOpenFile),
        TE_S1(RookOnSeventh), TE_S1(KnightOutpost), TE_S1(BishopOutpost), TE_S1(MinorBehindPawn),
        TE_S1(ThreatByPawn), TE_S1(ThreatMinorOnMajor), TE_S1(ThreatRookOnQueen), TE_S1(ThreatHanging),
        TE_S1(ThreatByKing), TE_S1(PawnPushThreat), TE_S1(Tempo), TE_S(KingShield), TE_S1(KingOpenFile),
        TE_S1(KingSemiOpenFile), TE_I(KingAttackWeight), TE_I(SafeCheckWeight), TE_I(KingDanger),
        TE_S1(BishopPawns), TE_S1(RookBehindPasser), TE_S(PawnStorm), TE_S1(KnightPawnCount), TE_S1(RookPawnCount), TE_S1(Space), TE_S1(PassedBlocked),
    };
}
