// Evaluation parameters. This file is (re)generated by the tuner; keep the format.
#pragma once

int mg_value[6] = {82, 337, 365, 477, 1025, 0};
int eg_value[6] = {94, 281, 297, 512, 936, 0};
int mg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
      68,  104,   31,   72,   66,   96,    4,  -41,
     -36,   -4,   -4,    2,   35,   26,   -5,  -31,
      -8,   -8,  -24,    3,   -7,    6,  -13,   -9,
     -38,  -24,  -18,   -4,  -11,   -8,   -3,  -18,
     -25,  -20,  -15,   -7,    2,    3,    9,  -10,
     -40,  -16,  -26,  -21,  -30,    6,    8,  -25,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int eg_pawn_table[64] = {
       0,    0,    0,    0,    0,    0,    0,    0,
     148,  143,  128,  105,  118,  102,  163,  157,
      64,   74,   55,   37,   26,   38,   53,   90,
      24,   -1,  -13,  -12,   -2,    2,  -11,   27,
      22,   22,   18,   -8,  -27,   18,   17,   24,
      28,   28,    3,  -15,   -7,   20,   12,   22,
     -13,   35,   36,   24,    5,    6,   12,   19,
       0,    0,    0,    0,    0,    0,    0,    0,
};
int mg_knight_table[64] = {
    -137,  -59,  -64,  -54,   89,  -81,    6,  -77,
     -44,  -60,   57,   41,   -5,   32,  -23,   11,
     -17,   30,   51,   37,   68,  130,   43,   66,
      21,   25,   24,   25,   18,   61,   24,   17,
      14,   34,   42,   13,   12,    7,   34,    6,
     -46,   15,   -1,  -20,   28,   -1,   41,  -31,
     -21,  -23,  -41,   10,    7,    4,  -16,  -29,
    -135,  -35,  -87,  -26,   -5,  -21,  -40,    7,
};
int eg_knight_table[64] = {
     -28,  -20,  -21,    1,  -37,  -40,  -42,  -69,
     -20,  -34,  -51,  -15,  -24,  -22,  -17,  -79,
     -34,  -32,  -16,    3,  -13,  -14,   10,  -65,
      10,  -26,   32,   33,   34,  -13,  -17,   -1,
      -8,   24,   14,   14,   46,  -12,  -21,  -22,
     -49,    5,   13,   28,    2,    9,  -40,    8,
     -22,   10,  -37,    3,  -20,   -4,  -36,  -27,
      -1,  -80,    7,  -45,   -1,   12,  -68,  -34,
};
int mg_bishop_table[64] = {
     -51,  -18, -111,  -67,    4,  -72,   35,  -38,
       4,  -14,  -48,   -8,   20,   29,  -12,  -49,
     -46,    8,   15,   15,    6,   20,   32,  -21,
     -34,  -14,  -10,   29,    7,   51,   11,   26,
       3,   33,   34,   35,   20,   38,   31,   32,
     -16,   37,  -14,    5,   -9,   -1,   34,  -20,
      33,    5,  -14,  -14,   -8,   18,   14,   30,
     -63,  -33,   -9,  -42,   16,  -13,  -27,    0,
};
int eg_bishop_table[64] = {
      16,  -43,  -11,  -28,   23,  -33,   11,    6,
     -38,   -5,   -1,    8,    7,   -7,   21,  -13,
      -3,   -1,    5,    9,   28,   36,   20,  -26,
      27,    9,  -18,   21,   16,  -20,   33,    9,
     -11,  -18,   10,    1,   37,  -11,   27,  -13,
      18,   23,   33,   -3,   42,    9,  -37,  -25,
     -13,   10,    7,   24,   28,  -19,  -35,    3,
       7,   21,   -7,   25,  -10,    0,   25,   13,
};
int mg_rook_table[64] = {
      47,   64,   62,   81,   66,   35,   56,   64,
      54,    3,   60,   54,   50,   44,   27,   70,
      22,    9,   -4,    8,   36,   65,   90,   24,
       5,  -20,   27,   54,   30,   50,   22,    4,
     -40,  -23,  -38,   -3,    1,  -22,   35,  -51,
     -15,  -38,  -15,  -45,  -17,   30,   -3,  -22,
     -14,  -14,   -2,  -37,  -18,  -17,   24,  -75,
     -10,  -13,    5,  -13,   -6,   -7,  -25,   -5,
};
int eg_rook_table[64] = {
      38,   40,   31,   38,   33,   28,   38,   35,
      39,   26,    6,    1,    3,    5,   26,   30,
      37,   30,   26,   34,   32,   18,   23,   27,
      15,   32,   23,  -17,    3,   11,   28,   32,
      29,   34,   38,   32,   25,   23,   22,   19,
      25,   30,   20,   11,   23,   18,   22,   14,
      10,   24,   29,   16,   15,    3,   19,   -8,
      21,   29,   20,   16,    9,    0,   33,   -1,
};
int mg_queen_table[64] = {
     -58,  -27,    9,    5,   88,   69,   16,   15,
     -54,  -28,   17,  -29,  -46,   27,   43,   24,
     -43,    9,  -23,  -22,    2,   26,   17,   30,
       3,  -22,  -32,   -1,  -17,  -13,   14,   13,
      11,  -43,    5,  -40,  -24,  -21,  -26,  -33,
     -41,  -28,   -2,  -21,  -35,  -24,   -3,  -25,
      -5,    5,   -9,   -4,  -16,  -13,   10,   30,
      29,  -28,  -27,  -12,   -7,    4,  -17,  -20,
};
int eg_queen_table[64] = {
      12,   48,   51,   57,   57,   39,   35,   50,
      -8,   50,   62,   71,   86,   38,   52,   30,
      10,   33,   39,   78,   64,   13,   49,  -16,
      26,   51,   52,   75,   83,   20,   47,   33,
      -8,   47,   27,   77,   58,   62,   24,   27,
      13,    0,   17,   29,   21,    8,   36,   35,
       4,  -11,   -6,    9,  -32,  -13,  -16,  -56,
      -5,   -6,  -34,  -72,   -5,   -5,  -23,  -34,
};
int mg_king_table[64] = {
     -84,   35,   30,   15,  -26,   -7,   27,   40,
       8,  -22,   10,    3,   22,  -33,  -55,  -25,
      20,   54,   -4,   12,    8,  -21,   -8,  -52,
      10,  -32,  -30,  -52,  -60,   -8,  -44,  -65,
     -79,   17,    1,  -11,  -41,  -55,  -37,  -53,
     -42,   16,    5,  -17,  -44,  -49,  -45,  -57,
       0,  -23,   -4,  -57,  -27,  -42,   -3,   20,
     -29,   38,   14,  -28,   -8,  -22,   36,   43,
};
int eg_king_table[64] = {
    -101,  -65,  -27,   11,  -24,    1,   -7,   13,
     -42,  -13,    5,    9,   47,    8,   -7,    6,
     -20,   47,   13,   45,   50,   15,   14,  -17,
     -12,   13,   54,   57,   49,   62,   31,  -15,
     -19,    4,   41,   53,   50,   44,    8,  -28,
     -49,  -19,   21,   22,   32,    9,    5,  -39,
     -32,   12,   -8,   31,    4,   12,   -3,  -39,
     -23,   -5,  -11,   -6,   -2,    2,  -16,  -71,
};
Score MobilityKnight[9] = {S(-21,-30), S(-14,-1), S(-18,18), S(-14,16), S(-7,13), S(-9,31), S(-1,33), S(3,13), S(-1,10)};
Score MobilityBishop[14] = {S(-28,-39), S(-30,-48), S(-14,1), S(-8,22), S(-5,13), S(0,42), S(3,46), S(-8,50), S(-7,47), S(-6,40), S(4,60), S(-2,48), S(59,20), S(5,40)};
Score MobilityRook[15] = {S(-68,-99), S(2,-56), S(-2,7), S(6,34), S(0,41), S(7,50), S(10,58), S(16,64), S(21,68), S(21,72), S(23,76), S(17,80), S(40,74), S(9,84), S(54,43)};
Score MobilityQueen[28] = {S(0,-20), S(-12,-60), S(-26,-45), S(-20,-40), S(-22,-30), S(-16,-17), S(-18,-16), S(-24,-4), S(-24,9), S(-16,30), S(-14,48), S(1,25), S(-13,43), S(-7,56), S(-16,70), S(-15,56), S(6,74), S(-12,67), S(8,78), S(3,78), S(-3,80), S(51,80), S(52,82), S(53,82), S(54,84), S(55,84), S(17,46), S(57,86)};
Score PassedRank[8] = {S(0,0), S(-28,31), S(-19,45), S(-25,56), S(-5,81), S(30,90), S(80,140), S(0,0)};
Score PawnIsolated = S(-1,0);
Score PawnDoubled = S(-13,-45);
Score PawnBackward = S(-12,-6);
Score PawnConnected[8] = {S(0,0), S(2,0), S(-1,13), S(7,-10), S(20,12), S(42,18), S(56,14), S(0,0)};
Score PawnPhalanx[8] = {S(0,0), S(4,-2), S(1,-4), S(11,0), S(7,41), S(70,60), S(100,90), S(0,0)};
Score BishopPair = S(-3,54);
Score RookOpenFile = S(30,22);
Score RookSemiOpenFile = S(8,38);
Score RookOnSeventh = S(16,45);
Score KnightOutpost = S(11,47);
Score BishopOutpost = S(-7,24);
Score MinorBehindPawn = S(6,20);
Score ThreatByPawn = S(63,25);
Score ThreatMinorOnMajor = S(64,10);
Score ThreatRookOnQueen = S(49,0);
Score ThreatHanging = S(18,50);
Score ThreatByKing = S(5,26);
Score PawnPushThreat = S(18,18);
Score Tempo = S(20,8);
Score KingShield[3] = {S(8,-18), S(-2,-22), S(1,-24)};
Score KingOpenFile = S(-14,-30);
Score KingSemiOpenFile = S(-6,7);
int KingAttackWeight[6] = {0, 15, 17, 19, 19, 0};
int SafeCheckWeight[6] = {0, 60, 36, 67, 80, 0};
int KingDanger[5] = {320, 39, 23, 150, 24};

int* mg_tables[6] = {mg_pawn_table, mg_knight_table, mg_bishop_table, mg_rook_table, mg_queen_table, mg_king_table};
int* eg_tables[6] = {eg_pawn_table, eg_knight_table, eg_bishop_table, eg_rook_table, eg_queen_table, eg_king_table};

#define TE_S(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(Score)), 0}
#define TE_S1(x) {#x, (void*)&x, 1, 0}
#define TE_I(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(int)), 1}
#define TE_P(x) {#x, (void*)x, 64, 2}
std::vector<TuneEntry> tune_entries() {
    return {
        {"mg_value", (void*)mg_value, 6, 3}, {"eg_value", (void*)eg_value, 6, 3},
        TE_P(mg_pawn_table), TE_P(eg_pawn_table), TE_P(mg_knight_table), TE_P(eg_knight_table),
        TE_P(mg_bishop_table), TE_P(eg_bishop_table), TE_P(mg_rook_table), TE_P(eg_rook_table),
        TE_P(mg_queen_table), TE_P(eg_queen_table), TE_P(mg_king_table), TE_P(eg_king_table),
        TE_S(MobilityKnight), TE_S(MobilityBishop), TE_S(MobilityRook), TE_S(MobilityQueen),
        TE_S(PassedRank), TE_S1(PawnIsolated), TE_S1(PawnDoubled), TE_S1(PawnBackward),
        TE_S(PawnConnected), TE_S(PawnPhalanx), TE_S1(BishopPair), TE_S1(RookOpenFile), TE_S1(RookSemiOpenFile),
        TE_S1(RookOnSeventh), TE_S1(KnightOutpost), TE_S1(BishopOutpost), TE_S1(MinorBehindPawn),
        TE_S1(ThreatByPawn), TE_S1(ThreatMinorOnMajor), TE_S1(ThreatRookOnQueen), TE_S1(ThreatHanging),
        TE_S1(ThreatByKing), TE_S1(PawnPushThreat), TE_S1(Tempo), TE_S(KingShield), TE_S1(KingOpenFile),
        TE_S1(KingSemiOpenFile), TE_I(KingAttackWeight), TE_I(SafeCheckWeight), TE_I(KingDanger),
    };
}
