// Texel-style coordinate-descent tuner for the evaluation parameters.
// Usage: tune.exe <datafile> <maxpositions> <iterations> <threads> <out params.h>
#include "eval.h"
#include <cstdio>
#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <thread>
#include <algorithm>
#include <chrono>

using namespace Eval;

struct Entry { Position pos; float result; };
static std::vector<Entry> data;
static double K = 1.0;
static int NTHREADS = 10;

static void recompute(Position& p) {
    p.mg = p.eg = p.phase = 0;
    U64 b = p.pieces();
    while (b) {
        int s = pop_lsb(b);
        int pc = p.board[s];
        int sign = piece_color(pc) == WHITE ? 1 : -1;
        p.mg += sign * PSQ_MG[pc][s];
        p.eg += sign * PSQ_EG[pc][s];
        p.phase += PhaseInc[piece_type(pc)];
    }
}

static double sigmoid(int v) { return 1.0 / (1.0 + std::pow(10.0, -K * v / 400.0)); }

static void error_range(size_t a, size_t b, double* out) {
    double e = 0;
    for (size_t i = a; i < b; i++) {
        Position& p = data[i].pos;
        recompute(p);
        int v = evaluate(p);
        if (p.stm == BLACK) v = -v;
        double d = data[i].result - sigmoid(v);
        e += d * d;
    }
    *out = e;
}

static double total_error() {
    std::vector<std::thread> th;
    std::vector<double> parts(NTHREADS, 0.0);
    size_t n = data.size();
    for (int t = 0; t < NTHREADS; t++)
        th.emplace_back(error_range, n * t / NTHREADS, n * (t + 1) / NTHREADS, &parts[t]);
    for (auto& t : th) t.join();
    double e = 0;
    for (double p : parts) e += p;
    return e / n;
}

struct Knob { TuneEntry e; int idx; int part; };  // part: 0 mg, 1 eg (for Score), 0 for int

static int get_knob(const Knob& k) {
    if (k.e.kind == 0) { Score s = ((Score*)k.e.ptr)[k.idx]; return k.part == 0 ? mg_of(s) : eg_of(s); }
    return ((int*)k.e.ptr)[k.idx];
}
static void set_knob(const Knob& k, int v) {
    if (k.e.kind == 0) {
        Score& s = ((Score*)k.e.ptr)[k.idx];
        int mg = mg_of(s), eg = eg_of(s);
        if (k.part == 0) mg = v; else eg = v;
        s = S(mg, eg);
    } else {
        ((int*)k.e.ptr)[k.idx] = v;
        if (k.e.kind == 2 || k.e.kind == 3) Eval::init();
    }
}

static void write_params(const char* file) {
    FILE* f = fopen(file, "w");
    fprintf(f, "// Evaluation parameters. This file is (re)generated by the tuner; keep the format.\n#pragma once\n\n");
    for (auto& e : tune_entries()) {
        if (e.kind == 0) {
            Score* p = (Score*)e.ptr;
            if (e.n == 1 && std::string(e.name).find('[') == std::string::npos && !(e.name[0] == 'M' && e.name[1] == 'o')) {
                // singles are declared without array syntax except known arrays
            }
            bool isArray = !(e.n == 1);
            // known single names
            if (e.n == 1) fprintf(f, "Score %s = S(%d,%d);\n", e.name, mg_of(p[0]), eg_of(p[0]));
            else {
                fprintf(f, "Score %s[%d] = {", e.name, e.n);
                for (int i = 0; i < e.n; i++) fprintf(f, "%sS(%d,%d)", i ? ", " : "", mg_of(p[i]), eg_of(p[i]));
                fprintf(f, "};\n");
            }
            (void)isArray;
        } else if (e.kind == 1 || e.kind == 3) {
            int* p = (int*)e.ptr;
            fprintf(f, "int %s[%d] = {", e.name, e.n);
            for (int i = 0; i < e.n; i++) fprintf(f, "%s%d", i ? ", " : "", p[i]);
            fprintf(f, "};\n");
        } else {
            int* p = (int*)e.ptr;
            fprintf(f, "int %s[64] = {\n", e.name);
            for (int r = 0; r < 8; r++) {
                fprintf(f, "   ");
                for (int c = 0; c < 8; c++) fprintf(f, " %4d,", p[r * 8 + c]);
                fprintf(f, "\n");
            }
            fprintf(f, "};\n");
        }
    }
    fprintf(f, "\nint* mg_tables[6] = {mg_pawn_table, mg_knight_table, mg_bishop_table, mg_rook_table, mg_queen_table, mg_king_table};\n");
    fprintf(f, "int* eg_tables[6] = {eg_pawn_table, eg_knight_table, eg_bishop_table, eg_rook_table, eg_queen_table, eg_king_table};\n\n");
    fprintf(f, "%s", R"(#define TE_S(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(Score)), 0}
#define TE_S1(x) {#x, (void*)&x, 1, 0}
#define TE_I(x) {#x, (void*)x, (int)(sizeof(x)/sizeof(int)), 1}
#define TE_P(x) {#x, (void*)x, 64, 2}
std::vector<TuneEntry> tune_entries() {
    return {
        {"mg_value", (void*)mg_value, 6, 3}, {"eg_value", (void*)eg_value, 6, 3},
        TE_P(mg_pawn_table), TE_P(eg_pawn_table), TE_P(mg_knight_table), TE_P(eg_knight_table),
        TE_P(mg_bishop_table), TE_P(eg_bishop_table), TE_P(mg_rook_table), TE_P(eg_rook_table),
        TE_P(mg_queen_table), TE_P(eg_queen_table), TE_P(mg_king_table), TE_P(eg_king_table),
        TE_S(MobilityKnight), TE_S(MobilityBishop), TE_S(MobilityRook), TE_S(MobilityQueen),
        TE_S(PassedRank), TE_S1(PawnIsolated), TE_S1(PawnDoubled), TE_S1(PawnBackward),
        TE_S(PawnConnected), TE_S(PawnPhalanx), TE_S1(BishopPair), TE_S1(RookOpenFile), TE_S1(RookSemiOpenFile),
        TE_S1(RookOnSeventh), TE_S1(KnightOutpost), TE_S1(BishopOutpost), TE_S1(MinorBehindPawn),
        TE_S1(ThreatByPawn), TE_S1(ThreatMinorOnMajor), TE_S1(ThreatRookOnQueen), TE_S1(ThreatHanging),
        TE_S1(ThreatByKing), TE_S1(PawnPushThreat), TE_S1(Tempo), TE_S(KingShield), TE_S1(KingOpenFile),
        TE_S1(KingSemiOpenFile), TE_I(KingAttackWeight), TE_I(SafeCheckWeight), TE_I(KingDanger),
    };
}
)");
    fclose(f);
}

int main(int argc, char** argv) {
    if (argc < 6) { printf("usage: tune <datafile> <maxpos> <iters> <threads> <out>\n"); return 1; }
    BB::init(); Zobrist::init(); Eval::init();
    Eval::UsePawnHash = false;
    size_t maxpos = strtoull(argv[2], 0, 10);
    int iters = atoi(argv[3]);
    NTHREADS = atoi(argv[4]);
    const char* outfile = argv[5];

    std::ifstream in(argv[1]);
    std::string line;
    data.reserve(maxpos);
    while (std::getline(in, line) && data.size() < maxpos) {
        size_t p1 = line.find('|');
        if (p1 == std::string::npos) continue;
        size_t p2 = line.find('|', p1 + 1);
        if (p2 == std::string::npos) continue;
        Entry e;
        e.pos.set_fen(line.substr(0, p1));
        e.result = (float)atof(line.c_str() + p2 + 1);
        data.push_back(e);
    }
    printf("loaded %zu positions\n", data.size());
    fflush(stdout);

    // find K
    double bestE = 1e9, bestK = 1.0;
    for (double k = 0.4; k <= 2.0; k += 0.1) {
        K = k;
        double e = total_error();
        if (e < bestE) { bestE = e; bestK = k; }
    }
    for (double k = bestK - 0.09; k <= bestK + 0.09; k += 0.02) {
        K = k;
        double e = total_error();
        if (e < bestE) { bestE = e; bestK = k; }
    }
    K = bestK;
    printf("K = %.3f  initial error %.6f\n", K, bestE);
    fflush(stdout);

    std::vector<Knob> knobs;
    for (auto& e : tune_entries()) {
        if (e.kind == 3) continue;
        for (int i = 0; i < e.n; i++) {
            if (e.kind == 0) { knobs.push_back({e, i, 0}); knobs.push_back({e, i, 1}); }
            else if (e.kind == 2) {
                // skip pawn rank 1/8 entries (always 0)
                if (std::string(e.name).find("pawn") != std::string::npos && (i < 8 || i >= 56)) continue;
                knobs.push_back({e, i, 0});
            } else knobs.push_back({e, i, 0});
        }
    }
    printf("%zu knobs\n", knobs.size());
    fflush(stdout);

    double cur = bestE;
    for (int it = 0; it < iters; it++) {
        int step = it < 2 ? 8 : (it < 4 ? 4 : (it < 6 ? 2 : 1));
        int improved = 0;
        auto t0 = std::chrono::steady_clock::now();
        for (size_t ki = 0; ki < knobs.size(); ki++) {
            Knob& k = knobs[ki];
            int v = get_knob(k);
            int st = step;
            // king danger divisor params need bigger steps
            if (std::string(k.e.name) == "KingDanger" && k.idx == 0) st = step * 8;
            set_knob(k, v + st);
            double e = total_error();
            if (e < cur) { cur = e; improved++; continue; }
            set_knob(k, v - st);
            e = total_error();
            if (e < cur) { cur = e; improved++; continue; }
            set_knob(k, v);
        }
        double secs = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
        printf("iter %d step %d error %.6f improved %d (%.0fs)\n", it, step, cur, improved, secs);
        fflush(stdout);
        write_params(outfile);
        if (improved == 0 && step == 1) break;
    }
    write_params(outfile);
    printf("done\n");
    return 0;
}
